### ISSUE TITLE
"nonspacing mark" unicode causes container's width to shift

### ISSUE THREAD

**Issue by OnFireByte** [charmbracelet/lipgloss#258] opened 2024-02-08 11:32 UTC
**Describe the bug**
Nonspacing mark unicodes are a type of character that doesn't consume space; instead, they "attach" themselves to the previous character. For example, "ี" or "ุ" are nonspacing marks commonly attached to another character like "ด," resulting in "ดี" or "ดุ."

When there are nonspacing mark unicodes inside lipgloss's container, the layout will shift on that line because lipgloss counts these characters as normal unicode that occupy 1 space.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - macOS
 - zsh
 - iterm2
 - th_TH.UTF-8

**To Reproduce**
1. Create a style with a fixed width, such as 16 characters.
2. Render it with a string that has nonspacing mark unicodes, for example, "สวัสดี." ("ั" and "ี" are nonspacing marks)
3. See the layout shift.

**Source Code**
```go
package main

import (
	"fmt"

	"github.com/charmbracelet/lipgloss"
)

var box = lipgloss.NewStyle().Width(8).Height(8).Border(lipgloss.RoundedBorder())

func main() {
	fmt.Println(box.Render("สวัสดี"))
}
```

**Screenshots**
<img width="155" alt="image" src="https://github.com/charmbracelet/lipgloss/assets/65996113/af5fc160-7bec-44b8-b20e-88077f4bdac9">

**Comment by mikelorant** [comment] 2024-02-13 01:37
This is a known issue that is pending these pull requests:
- #257 
- muesli/reflow#71

Without these being merged, the problem cannot be resolved. For context, this is due to incorrect rune width calculations not handling grapheme clusters (which obviously understand ZWJ).

**Comment by mikelorant** [comment] 2024-02-16 05:23
Confirmed this is fixed with the pull requests I have listed above:
![CleanShot 2024-02-16 at 16 23 20](https://github.com/charmbracelet/lipgloss/assets/215265/34f28046-9ae6-41d2-808e-00ee9168fc29)

**Comment by OnFireByte** [comment] 2024-02-16 15:14
Look like it's fixed on master branch now, thank!

**Closed** 2024-03-29 19:05 UTC
