### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by pinpox** [charmbracelet/lipgloss#265] opened 2024-02-26 11:14 UTC
**Describe the bug**
I'm trying to build the [example code](https://gist.github.com/pinpox/bb3239afd744f8bb05e18505f83afd7d) for `charmbracelet/huh`. When running `go run main.go` I get this error from lipgloss:

```
❯ go get github.com/charmbracelet/lipgloss@v0.9.1
verifying github.com/charmbracelet/lipgloss@v0.9.1/go.mod: checksum mismatch
        downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
        go.sum:     h1:1mPmG4cxScwUQALAAnacHaigiiHB9Pmr+v1VEawJl6I=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

I have attached `go.mod` and `go.sum` in the [gist](https://gist.github.com/pinpox/bb3239afd744f8bb05e18505f83afd7d)

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS NixOS
 - Shell zsh
 - Terminal Emulator foot
 - Terminal Multiplexer zellij
 - Locale en_US.UTF-8

**To Reproduce**
1. Save `main.go`, `go.mod` and `go.sum` liked above to a folder
2. run `go run main.go`
3. See error

**Source Code**
[gist](https://gist.github.com/pinpox/bb3239afd744f8bb05e18505f83afd7d)

**Expected behavior**
example runs

**Comment by meowgorithm** [comment] 2024-02-26 20:46
This looks like it may be an issue with your local cache or Go proxy. I'd recommend `go mod tidy` — and barring that regenerating your `go.sum`. If that doesn't help I'd suggest rebuilding the contents of your `GOPATH`.

We're not able to reproduce this internally.

**Comment by mikelorant** [comment] 2024-02-26 23:10
Confirmed using those files that it requires a `go mod tidy`.

This issue should be closed as this is clearly a tooling error and has nothing to do with Lipgloss.

**Comment by pinpox** [comment] 2024-02-26 23:19
Okay something borked in my side then, sorry to bother.

**Closed** 2024-02-26 23:19 UTC
